LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := start
LOCAL_SRC_FILES := start.elf
LOCAL_MODULE_SUFFIX := .elf
LOCAL_MODULE_OWNER := broadcom
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/bootloader
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := fixup
LOCAL_SRC_FILES := fixup.dat
LOCAL_MODULE_SUFFIX := .dat
LOCAL_MODULE_OWNER := broadcom
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/bootloader
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bootcode
LOCAL_SRC_FILES := bootcode.bin
LOCAL_MODULE_SUFFIX := .bin
LOCAL_MODULE_OWNER := broadcom
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := FIRMWARE
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/bootloader
include $(BUILD_PREBUILT)


